### ISSUE TITLE
RTC_C output VAR LDT gives error

### ISSUE THREAD

**Issue by warwolf7** [stefandreyer/CODESYS-MQTT#45]
Hi, in the timeDate\RTC_2  FB, the VAR_OUTPUT LDT is giving me an error. Can this be happenning because of the LDT data type already in  codesys?
https://help.codesys.com/api-content/2/codesys/3.5.16.0/en/_cds_datatype_date_and_time_of_day/

Should this variable be renamed?

**Comment by warwolf7** [comment]
it's an error that comes up with the compiler 3.5.16.0. It does not happens with compiler 3.5.12.0

**Comment by annD-annD** [comment]
I think you are right. Here is some information:
[http://www.oscat.de/community/index.php/topic,5794.msg18140.html](url)

You can try my version from here:
[https://github.com/stefandreyer/CODESYS-MQTT/issues/41#issuecomment-645533894](url)

**Comment by stefandreyer** [comment]
Hi,

I Update my libs allready, need to publish them...

BR Stefan

**Comment by Tommilein** [comment]
Hallo Stefan,
we had a problem with oscat basic in July 2019 already:
![problem_oscat_072020](https://user-images.githubusercontent.com/46820950/89917463-2017ed00-dbf9-11ea-9dda-f10320317670.jpg)

I hope it helps to remember because it sounds like the current.

And now I have the same problems like warwolf7. I made an upgrade to 3.5.16 and nothing functions.
![problem_oscat_B_072020](https://user-images.githubusercontent.com/46820950/89917823-8ef54600-dbf9-11ea-95ce-7dab601ba343.jpg)


I hope you can publish the new libraries in a short time. Your library is in production (smile) !! 

beste Grüße
Thomas

**Comment by stefandreyer** [comment]
Hi,

libs are up to date, please have a look.

BR Stefan

**Comment by Tommilein** [comment]
Hallo,
I tried the Lib and got 3 Errors. I changed the MQTT-Lib only and now I have two different versions of OSCAT-Basic in the library manager.
![Codesys_MQTT_ERR_1](https://user-images.githubusercontent.com/46820950/93080246-abb7ea00-f68d-11ea-8387-1f12008310f2.jpg)

Is it enough to change to the MQTT-Lib "MQTT 1.1.0.3.library"  only?

bye
Thomas

**Comment by stefandreyer** [comment]
Hi Thomas,

try to remove your version of OSCAT Basic of the repositiory and to work with my only.

I think this should help.

BR Stefan

**Comment by Tommilein** [comment]
Hi Stefan,
the OSCAT-BASIC-Lib is not in the zip-File. Where can i find it or must i export the Lib from MQTT-Lib?
I have problems to understand the library manager.

Thomas

Edit: it functions now, but I don't know, why. Sorry...

**Comment by stefandreyer** [comment]
Hi,

sounds good...

have fun!
